apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventbus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: eventbus
  template:
    metadata:
      labels:
        component: eventbus
    spec:
      containers:
        - name: eventbus
          image: <eventbus-image>
          ports:
            - containerPort: 4005
---
apiVersion: v1
kind: Service
metadata:
  name: eventbus-service
spec:
  selector:
    component: eventbus
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4005